name: Build and Release (Self-hosted)

on:
    push:
      tags:
        - '*'

jobs:
  build:
    name: Build Images
    permissions: write-all
    runs-on: self-hosted
    outputs:
      regular_build: ${{ steps.regular_build.outputs.success }}
    
    steps:
      - name: Install and update dependencies
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y gcc make git unzip wget xz-utils bc gperf zip g++ xfonts-utils xsltproc \
            openjdk-11-jre-headless libparse-yapp-perl libxml-parser-perl patchutils lzop rdfind dotnet-sdk-9.0

      - name: Update repository
        working-directory: /home/bubbles/TKMM-NX
        run: |
          git fetch --all --tags -f
          git checkout ${{ github.ref_name }} -f
          
      - name: Build regular image
        id: regular_build
        working-directory: /home/bubbles/TKMM-NX
        run: |
          mkdir -p releases
          rm -rf target/*
          THREADCOUNT=20 DISTRO=TKMM PROJECT=L4T DEVICE=Switch ARCH=aarch64 make image
          for file in target/TKMM-Switch.*; do
            if [ -f "$file" ]; then
              commit=$(echo "$file" | sed -E 's/.*-([a-f0-9]+)\.[^.]+(\.[^.]+)?$/\1/')
              if [[ "$file" == *.tar.sha256 ]]; then
                mv "$file" "releases/TKMM-NX-${{ github.ref_name }}-${commit}.tar.sha256"
              else
                ext="${file##*.}"
                mv "$file" "releases/TKMM-NX-${{ github.ref_name }}-${commit}.${ext}"
              fi
            fi
          done
          echo "success=true" >> $GITHUB_OUTPUT

      - name: Build debug image
        id: debug_build
        working-directory: /home/bubbles/TKMM-NX
        continue-on-error: true
        run: |
          mkdir -p debug
          THREADCOUNT=20 DISTRO=TKMM PROJECT=L4T DEVICE=Switch ARCH=aarch64 DEVMODE=enabled make image
          for file in target/TKMM-Switch.*; do
            if [ -f "$file" ]; then
              commit=$(echo "$file" | sed -E 's/.*-([a-f0-9]+)\.[^.]+(\.[^.]+)?$/\1/')
              if [[ "$file" == *.tar.sha256 ]]; then
                mv "$file" "debug/TKMM-NX-${{ github.ref_name }}-DEBUG-${commit}.tar.sha256"
              else
                ext="${file##*.}"
                mv "$file" "debug/TKMM-NX-${{ github.ref_name }}-DEBUG-${commit}.${ext}"
              fi
            fi
          done

  release:
    needs: build
    if: needs.build.outputs.regular_build == 'true'
    name: Create Release
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      release: ${{ steps.release.outputs.upload_url }}

    steps:
      - name: Create Release
        uses: actions/create-release@v1
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: TKMM-NX - ${{ github.ref_name }}
          draft: false
          prerelease: false

  upload:
    name: Upload Images
    needs: [build, release]
    permissions: write-all
    runs-on: self-hosted
    
    steps:
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            /home/bubbles/TKMM-NX/releases/*
            /home/bubbles/TKMM-NX/debug/*

      - name: Upload to mirror
        working-directory: /home/bubbles/TKMM-NX
        run: |
          scp -i ~/.ssh/github_runner_sftp_key releases/* ubuntu@repo.tkmm.org:/var/www/html/repo/.tkmm-nx/Releases
          scp -i ~/.ssh/github_runner_sftp_key debug/* ubuntu@repo.tkmm.org:/var/www/html/repo/.tkmm-nx/Debug

      - name: Cleanup Folders
        run: |
          rm -rf /home/bubbles/TKMM-NX/releases
          rm -rf /home/bubbles/TKMM-NX/debug