name: Build and Release (Self-hosted)

on:
    push:
      tags:
        - '*'

jobs:
  build:
    name: Build Images
    permissions: write-all
    runs-on: bubbles
    outputs:
      regular_build: ${{ steps.regular_build.outputs.success }}
    
    steps:
      - name: Install and update dependencies
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y gcc make git unzip wget xz-utils bc gperf zip g++ xfonts-utils xsltproc \
            openjdk-11-jre-headless libparse-yapp-perl libxml-parser-perl patchutils lzop rdfind
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh && chmod +x dotnet-install.sh && ./dotnet-install.sh --channel 9.0
          rm dotnet-install.sh

      - name: Update repository
        working-directory: /home/bubbles/TKMM-NX
        run: |
          git fetch --all --tags -f
          git checkout ${{ github.ref_name }} -f
          
      - name: Build regular image
        id: regular_build
        working-directory: /home/bubbles/TKMM-NX
        run: |
          export PATH="/home/bubbles/.dotnet:$PATH"
          rm -rf releases && mkdir -p releases
          rm -rf target/*
          DISTRO=TKMM PROJECT=L4T DEVICE=Switch ARCH=aarch64 scripts/clean tkmm
          DISTRO=TKMM PROJECT=L4T DEVICE=Switch ARCH=aarch64 scripts/clean samba
          DISTRO=TKMM PROJECT=L4T DEVICE=Switch ARCH=aarch64 scripts/clean linux
          DISTRO=TKMM PROJECT=L4T DEVICE=Switch ARCH=aarch64 scripts/clean kernel
          DISTRO=TKMM PROJECT=L4T DEVICE=Switch ARCH=aarch64 scripts/clean initramfs
          THREADCOUNT=20 DISTRO=TKMM PROJECT=L4T DEVICE=Switch ARCH=aarch64 TKMM_VERSION=${{ github.ref_name }} make image
          mv target/* releases/
          echo "success=true" >> $GITHUB_OUTPUT

      - name: Build debug image
        id: debug_build
        working-directory: /home/bubbles/TKMM-NX
        continue-on-error: true
        run: |
          export PATH="/home/bubbles/.dotnet:$PATH"
          rm -rf debug && mkdir -p debug
          THREADCOUNT=20 DISTRO=TKMM PROJECT=L4T DEVICE=Switch ARCH=aarch64 DEVMODE=enabled TKMM_VERSION=${{ github.ref_name }} make image
          mv target/* debug/

  release:
    needs: build
    if: needs.build.outputs.regular_build == 'true'
    name: Create Release
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      release: ${{ steps.release.outputs.upload_url }}

    steps:
      - name: Create Release
        uses: actions/create-release@v1
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: TKMM-NX - ${{ github.ref_name }}
          draft: false
          prerelease: false

  upload:
    name: Upload Images
    needs: [build, release]
    permissions: write-all
    runs-on: bubbles
    
    steps:
      - name: Upload to mirror
        working-directory: /home/bubbles/TKMM-NX
        run: |
          scp -i ~/.ssh/github_runner_sftp_key releases/* ubuntu@repo.tkmm.org:/var/www/html/repo/.tkmm-nx/Releases
          scp -i ~/.ssh/github_runner_sftp_key debug/* ubuntu@repo.tkmm.org:/var/www/html/repo/.tkmm-nx/Debug

      - name: Normalize zip file name for GitHub release
        working-directory: /home/bubbles/TKMM-NX
        run: |
          mv releases/*.system releases/SYSTEM
          mv releases/*.zip releases/tkmm-nx.zip

      - name: Create Checksum File
        working-directory: /home/bubbles/TKMM-NX
        run: |
          md5=($(md5sum -b releases/SYSTEM))
          echo $md5 > releases/SYSTEM.checksum

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            /home/bubbles/TKMM-NX/releases/SYSTEM
            /home/bubbles/TKMM-NX/releases/SYSTEM.checksum
            /home/bubbles/TKMM-NX/releases/tkmm-nx.zip
            /home/bubbles/TKMM-NX/releases/update.tar

      - name: Cleanup Folders
        run: |
          rm -rf /home/bubbles/TKMM-NX/releases
          rm -rf /home/bubbles/TKMM-NX/debug